### ISSUE TITLE
display status of group quest

### ISSUE THREAD

**Issue by mschaaf** [remjey/HabitSailor#2]
* what quest is running
* what is the boss life status
* i am joined the quest or not
* allow to join the quest
* show chat messages
* allow to send messages

**Comment by remjey** [comment]
Work has begun in the “party” branch

**Comment by mschaaf** [comment]
Thank you.

**Comment by remjey** [comment]
Everything is implemented and will be included in next release (soon)

**Comment by mschaaf** [comment]
Thanks a lot, I will have a look at it.
